environment.txt replace with workflowInfo.json
telia-actions/fft-actions pull request #19
Opened 2022-05-03 14:06 UTC by SSinkus

2022-05-05 09:26 UTC, ech018 commented
Do you @telia-actions/transistor think that `author_email` should be inside `slack-payload` action?

`slack-payload` is creating a message payload, it should not care about persons or channels we going to send message to. Author email is required for `https://github.com/telia-actions/look-up-slack-user`.

2022-05-05 10:47 UTC, SSinkus commented
I agree, that we could move author_email parsing to [look-up-slack-user](https://github.com/telia-actions/look-up-slack-user), if we would move `look-up-slack-user` to our actions monorepo. Then we would need to think about some common libs, otherwise we would duplicate code for get PR attachments, artifactId and other methods. But for this moment we need working solution, and this one could be added to backlog as improvement. And I still believe that we invested too much time to these notifications - nice to have feature tho.

2022-05-05 11:08 UTC, raihle requested changes

2022-05-05 11:08 UTC, raihle commented on actions/slack-payload/src/libs/workflow-context/workflow-context.ts
>  };
Instead of returning JSON, let's take responsibility for parsing the workflow info file - and make sure that the expected properties are there.

GitHub won't let me make a suggestion here, but something like this:

```ts
interface WorkflowInfo {
  environment: string;
  author_email: string;
}

const getArtifactContents = async (token: string, artifactId: number): Promise<Record<string, unknown>> => {
  try {
    const infoArtifact = await getArtifact(token, artifactId)
    const fileName = 'workflowInfo';
    writeFile(`${fileName}.zip`, Buffer.from(environmentArtifact as ArrayBuffer));
    await unzipArtifact(fileName);
    return JSON.parse(readFile(`${fileName}.json`));
  } catch {
    return {};
  }
}
const addMissingWorkflowInfoProperties = (partialInfo: Record<string, unknown>): WorkflowInfo => {
  return {
    environment: 'Unknown',
    author_email: 'Unknown',
    ...partialInfo,
  };
}
const getWorkflowInfo = async (token: string, artifactId: number): Promise<WorkflowInfo> => {
  const workflowInfo = await getArtifactContents(token, artifactId);
  return addMissingWorkflowInfoProperties(workflowInfo);
}
```

2022-05-05 11:08 UTC, raihle commented on actions/slack-payload/src/libs/workflow-context/workflow-context.ts
> +  const workflowInfo = JSON.parse(workflowInfoJson);
See also my suggestion for getWorkflowInfo
```suggestion
  const workflowInfo = workflowInfoArtifactId
    ? await getWorkflowInfo(token, workflowInfoArtifactId)
    : addMissingWorkflowInfoProperties({});
```

2022-05-05 11:08 UTC, raihle commented on actions/slack-payload/src/libs/workflow-context/workflow-context.ts
> +    environment: workflowInfo.environment || 'Unknown',
See also my suggestion for getWorkflowInfo
```suggestion
    environment: workflowInfo.environment,
```

2022-05-05 11:08 UTC, raihle commented on actions/slack-payload/src/libs/workflow-context/workflow-context.ts
> +    author_email: workflowInfo.author_email || 'Unknown',
See also my suggestion for getWorkflowInfo
```suggestion
    author_email: workflowInfo.author_email,
```

2022-05-05 11:23 UTC, raihle commented
Re: where to handle the email - 

I don't want to couple every action with environmentInfo.json. We have "Upload workflow Info" as a reusable workflow (why is it a workflow instead of an action?), and I think we should also have "Download workflow Info" as a workflow/action, which just reads the data to be used by other workflows/actions.

2022-05-05 11:58 UTC, ech018 commented
> I agree, that we could move author_email parsing to [look-up-slack-user](https://github.com/telia-actions/look-up-slack-user), if we would move `look-up-slack-user` to our actions monorepo. Then we would need to think about some common libs, otherwise we would duplicate code for get PR attachments, artifactId and other methods. But for this moment we need working solution, and this one could be added to backlog as improvement. And I still believe that we invested too much time to these notifications - nice to have feature tho.

I would rather have no solution than messy solution with mixed contexts.

2022-05-05 12:52 UTC, SSinkus commented
> > I agree, that we could move author_email parsing to [look-up-slack-user](https://github.com/telia-actions/look-up-slack-user), if we would move `look-up-slack-user` to our actions monorepo. Then we would need to think about some common libs, otherwise we would duplicate code for get PR attachments, artifactId and other methods. But for this moment we need working solution, and this one could be added to backlog as improvement. And I still believe that we invested too much time to these notifications - nice to have feature tho.
> 
> I would rather have no solution than messy solution with mixed contexts.

So at this moment with this messy solution as you call we would have working solution - developers will receive notifications. And then we could add to other sprint or later a task to refactor this solution. Because we would need introduce workflow or action as @raihle proposed.

2022-05-06 07:25 UTC, raihle requested changes

2022-05-06 07:25 UTC, raihle commented on actions/slack-payload/src/__tests__/github-action.test.ts
> +const mockedEmail = 'noreplay@telia.se';
```suggestion
const mockedEmail = 'noreply@telia.se';
```

2022-05-06 07:25 UTC, raihle commented on actions/slack-payload/src/__tests__/github-action.test.ts
> +      expect(setOutputSpy).toHaveBeenCalledTimes(2);
```suggestion
```

2022-05-06 07:25 UTC, raihle commented on actions/slack-payload/src/libs/workflow-context/__tests__/main-context.test.ts
> +  it('should fail', async () => {
```suggestion
  it('should list author and environment as "Unknown" when artifact contents are not valid JSON', async () => {
```

2022-05-06 07:25 UTC, raihle commented on actions/slack-payload/src/libs/workflow-context/__tests__/main-context.test.ts
>      });
Tests should not be more specific than they need to be

```suggestion
    expect(payload).toEqual(expect.objectContaining({
      environment: mockedWorkflowInfoOnFailure.environment,
      author_email: mockedWorkflowInfoOnFailure.author_email,
    }));
```

2022-05-06 07:25 UTC, raihle commented on actions/slack-payload/src/libs/workflow-context/workflow-context.ts
> +const mapPullRequestData = (pullRequest: PullRequest): PullRequestData | undefined => {
This is never going to return undefined
```suggestion
const mapPullRequestData = (pullRequest: PullRequest): PullRequestData => {
```

2022-05-06 13:15 UTC, raihle approved these changes

2022-05-06 13:26 UTC, merged